In [2]:
import os
import numpy as np
import pandas as pd

# 1.	Create a 2D array and print the dim and shape

In [4]:
a=np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [5]:
a.shape

(2, 4)

In [6]:
a.ndim

2

# 2.	Create an array of 20 numbers using arange function and slice the values between 10 to 15

In [9]:
b=np.arange(20)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [12]:
b[11:15]

array([11, 12, 13, 14])

# 3.	Create 2 arrays of 7X5 dimension and broadcast between the 2 arrays using 
a.	Addition
b.	Subtraction
c.	Multiplication
d.	Division


In [34]:
c1=np.arange(65,100).reshape(7,5)
c2=np.arange(35).reshape(7,5)


In [35]:
c1

array([[65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74],
       [75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84],
       [85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94],
       [95, 96, 97, 98, 99]])

In [36]:
c2

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34]])

In [39]:
c1+c2

array([[ 65,  67,  69,  71,  73],
       [ 75,  77,  79,  81,  83],
       [ 85,  87,  89,  91,  93],
       [ 95,  97,  99, 101, 103],
       [105, 107, 109, 111, 113],
       [115, 117, 119, 121, 123],
       [125, 127, 129, 131, 133]])

In [40]:
c1-c2

array([[65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65],
       [65, 65, 65, 65, 65]])

In [41]:
c1*c2

array([[   0,   66,  134,  204,  276],
       [ 350,  426,  504,  584,  666],
       [ 750,  836,  924, 1014, 1106],
       [1200, 1296, 1394, 1494, 1596],
       [1700, 1806, 1914, 2024, 2136],
       [2250, 2366, 2484, 2604, 2726],
       [2850, 2976, 3104, 3234, 3366]])

In [42]:
c1/c2

C:\Users\GODWIN~1\AppData\Local\Temp/ipykernel_14808/2927223530.py:1: RuntimeWarning: divide by zero encountered in true_divide
  c1/c2


array([[        inf, 66.        , 33.5       , 22.66666667, 17.25      ],
       [14.        , 11.83333333, 10.28571429,  9.125     ,  8.22222222],
       [ 7.5       ,  6.90909091,  6.41666667,  6.        ,  5.64285714],
       [ 5.33333333,  5.0625    ,  4.82352941,  4.61111111,  4.42105263],
       [ 4.25      ,  4.0952381 ,  3.95454545,  3.82608696,  3.70833333],
       [ 3.6       ,  3.5       ,  3.40740741,  3.32142857,  3.24137931],
       [ 3.16666667,  3.09677419,  3.03125   ,  2.96969697,  2.91176471]])

# 4.	Create 2 incompatible arrays for broadcast and print out the error

In [43]:
d1=np.array([[1,2,3],[4,5,6]])
d2=np.array([[1,2],[4,5]])

In [44]:
d1+d2

ValueError: operands could not be broadcast together with shapes (2,3) (2,2) 

# 5.	Create two arrays of any dimension and perform vstack and hstack

In [45]:
x = np.array([[1,2],[3,4],[5,6]])  
y = np.array([[10,20],[30,40],[50,60]])

In [46]:
xy=np.hstack((x,y))
xy

array([[ 1,  2, 10, 20],
       [ 3,  4, 30, 40],
       [ 5,  6, 50, 60]])

In [47]:
xy=np.vstack((x,y))
xy

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [10, 20],
       [30, 40],
       [50, 60]])

# 6.	Append two arrays using axis = 0 and axis = 1

In [48]:
xy=np.stack((x,y), axis=0)
xy

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6]],

       [[10, 20],
        [30, 40],
        [50, 60]]])

In [49]:
xy=np.stack((x,y), axis=1)
xy

array([[[ 1,  2],
        [10, 20]],

       [[ 3,  4],
        [30, 40]],

       [[ 5,  6],
        [50, 60]]])

# 7.	Create a dataframe for 8 X 4 dimension using list of lists and name the columns while dataframe creation

In [51]:
df=pd.DataFrame(list(range(8))
df

0
0  0
1  1
2  2
3  3
4  4
5  5
6  6
7  7

In [66]:
list1=[55,52,44,56,58,39,41,29]
list2=[14,15,18,21,15,16,17,18]
list3=['M','F','M','F','M','F','M','F']
list4=['Pa','Ab','Fg','Hg','Jk','Pl','Yk','Rk']
df1=pd.DataFrame(list1,columns=['average'])
df1

average
0       55
1       52
2       44
3       56
4       58
5       39
6       41
7       29

In [69]:
df1['age']=list2
df1['Gender']=list3
df1['Name']=list4
df1

average  age Gender Name
0       55   14      M   Pa
1       52   15      F   Ab
2       44   18      M   Fg
3       56   21      F   Hg
4       58   15      M   Jk
5       39   16      F   Pl
6       41   17      M   Yk
7       29   18      F   Rk

# 8.	Create a dataframe of 4 X 8 dimension using a dictionary

In [6]:
dict1={'CSK':[1,2,2,3],'MI':[3,4,1,4],'RCB':[2,5,6,5],'RR':[5,6,4,5],'SRH':[7,5,8,6],'KXIP':[5,7,8,2],'KKR':[4,1,5,1],'DD':[8,6,6,5]}
df2=pd.DataFrame(dict1,index=['2011','2012','2013','2014'])
df2

CSK  MI  RCB  RR  SRH  KXIP  KKR  DD
2011    1   3    2   5    7     5    4   8
2012    2   4    5   6    5     7    1   6
2013    2   1    6   4    8     8    5   6
2014    3   4    5   5    6     2    1   5

# 9.	Use loc and iloc to subset the data for the above dataframe

In [42]:
df2.loc['2012':'2014',['CSK','RCB','MI']]

CSK  RCB  MI
2012    2    5   4
2013    2    6   1
2014    3    5   4

In [48]:
df2.iloc[[0,1,2],0:3]

CSK  MI  RCB
2011    1   3    2
2012    2   4    5
2013    2   1    6

# 10.	How to check the total number of not null values in a column?

In [49]:
df2['MI'].notnull()

2011    True
2012    True
2013    True
2014    True
Name: MI, dtype: bool

# 11.	Create a dataframe with missing values and fill them all with 100

In [54]:
d2={'state':[1,2,3],
    'city':[4,5,6],
    'const':[7,8,9],
    'No_of_school':[10,11,12]}
da1=pd.DataFrame(d2)

dict2 = {'state': ['Tamilnadu','telangana','karanataka'], 
        'city': ['Chennai','Hyderabad','Banglore'], 
         'const': [10,20,30], 
         'No_of_school': [100,200,300]}
df4 = pd.DataFrame(dict2)
df5=da1.append(df4)
df5

state       city  const  No_of_school
0           1          4      7            10
1           2          5      8            11
2           3          6      9            12
0   Tamilnadu    Chennai     10           100
1   telangana  Hyderabad     20           200
2  karanataka   Banglore     30           300

In [56]:
df6=pd.concat([df5,df2])
df6

state       city  const  No_of_school  CSK   MI  RCB   RR  SRH  \
0              1          4    7.0          10.0  NaN  NaN  NaN  NaN  NaN   
1              2          5    8.0          11.0  NaN  NaN  NaN  NaN  NaN   
2              3          6    9.0          12.0  NaN  NaN  NaN  NaN  NaN   
0      Tamilnadu    Chennai   10.0         100.0  NaN  NaN  NaN  NaN  NaN   
1      telangana  Hyderabad   20.0         200.0  NaN  NaN  NaN  NaN  NaN   
2     karanataka   Banglore   30.0         300.0  NaN  NaN  NaN  NaN  NaN   
2011         NaN        NaN    NaN           NaN  1.0  3.0  2.0  5.0  7.0   
2012         NaN        NaN    NaN           NaN  2.0  4.0  5.0  6.0  5.0   
2013         NaN        NaN    NaN           NaN  2.0  1.0  6.0  4.0  8.0   
2014         NaN        NaN    NaN           NaN  3.0  4.0  5.0  5.0  6.0   

      KXIP  KKR   DD  
0      NaN  NaN  NaN  
1      NaN  NaN  NaN  
2      NaN  NaN  NaN  
0      NaN  NaN  NaN  
1      NaN  NaN  NaN  
2      NaN  NaN  NaN  
2011   5.0  4.0  8.0  
2012   7.0  1.0  6.0  
2013   8.0  5.0  6.0  
2014   2.0  1.0  5.0

In [57]:
df6.fillna(100)

state       city  const  No_of_school    CSK     MI    RCB     RR  \
0              1          4    7.0          10.0  100.0  100.0  100.0  100.0   
1              2          5    8.0          11.0  100.0  100.0  100.0  100.0   
2              3          6    9.0          12.0  100.0  100.0  100.0  100.0   
0      Tamilnadu    Chennai   10.0         100.0  100.0  100.0  100.0  100.0   
1      telangana  Hyderabad   20.0         200.0  100.0  100.0  100.0  100.0   
2     karanataka   Banglore   30.0         300.0  100.0  100.0  100.0  100.0   
2011         100        100  100.0         100.0    1.0    3.0    2.0    5.0   
2012         100        100  100.0         100.0    2.0    4.0    5.0    6.0   
2013         100        100  100.0         100.0    2.0    1.0    6.0    4.0   
2014         100        100  100.0         100.0    3.0    4.0    5.0    5.0   

        SRH   KXIP    KKR     DD  
0     100.0  100.0  100.0  100.0  
1     100.0  100.0  100.0  100.0  
2     100.0  100.0  100.0  100.0  
0     100.0  100.0  100.0  100.0  
1     100.0  100.0  100.0  100.0  
2     100.0  100.0  100.0  100.0  
2011    7.0    5.0    4.0    8.0  
2012    5.0    7.0    1.0    6.0  
2013    8.0    8.0    5.0    6.0  
2014    6.0    2.0    1.0    5.0

# 12.	Create a dataframe with missing values and drop the null records

In [62]:
df7=pd.DataFrame(np.random.randn(4,2),index=['a','c','d','g'],columns=['One','Two'])
df7

One       Two
a  1.040186 -0.264004
c -1.067547  1.758009
d  0.281270 -0.298975
g  1.299035  0.678749

In [63]:
df7 = df7.reindex(['a', 'b', 'c', 'd', 'e','f', 'g', 'h'])
df7

One       Two
a  1.040186 -0.264004
b       NaN       NaN
c -1.067547  1.758009
d  0.281270 -0.298975
e       NaN       NaN
f       NaN       NaN
g  1.299035  0.678749
h       NaN       NaN

In [64]:
df7.dropna()

One       Two
a  1.040186 -0.264004
c -1.067547  1.758009
d  0.281270 -0.298975
g  1.299035  0.678749

# 13.	Perform following aggregation task on below table
a.	Get the average age group by Regrion
b.	Get the sum of Age and Validation group by Hair color and then reset the index
c.	Get the man and the median of Age group by Region


In [68]:
df8={'Age':[25,30,45,35,33,35,25,52,21,24,48,22,27,28,21,51,23],
    'Hair Color':['Black','Black','Red','Blond','Brown','Brown','Black','Brown','Blond','Blond','Black','Black','Brown','Black','Blond','Black','Brown'],
    'U.S Region':['Southwest','Northwest','Northeast','Southwest','Southwest','Northeast','Southwest','Southeast','Southwest','Northeast','Southwest','Southwest','Northeast','Southeast','Northeast','Northwest','Southeast'],
    'Validation':[1,1,1,0,0,0,0,0,1,0,1,0,0,1,1,0,1]}
da5=pd.DataFrame(df8)
da5

Age Hair Color U.S Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Northeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [76]:
da5['Age'].mean(0)

32.05882352941177

In [83]:
import warnings
warnings.filterwarnings('ignore')

In [84]:
da5.groupby(['Hair Color'])['Age','Validation'].sum().reset_index()

Hair Color  Age  Validation
0      Black  229           4
1      Blond  101           2
2      Brown  170           1
3        Red   45           1

In [87]:
da5.groupby(['U.S Region'])['Age'].mean().reset_index()

U.S Region        Age
0  Northeast  30.400000
1  Northwest  40.500000
2  Southeast  34.333333
3  Southwest  29.857143

In [88]:
da5.groupby(['U.S Region'])['Age'].median().reset_index()

U.S Region   Age
0  Northeast  27.0
1  Northwest  40.5
2  Southeast  28.0
3  Southwest  25.0

# 14.	Split the below table into half and perform merge (inner, left and right) on Region. One example for each type of merge (inner, left and right)


In [105]:
half=len(da5)//2
da5_left = da5.iloc[:half , :]
da5_right=da5.iloc[half: , : ]


In [106]:
da5_left

Age Hair Color U.S Region  Validation
0   25      Black  Southwest           1
1   30      Black  Northwest           1
2   45        Red  Northeast           1
3   35      Blond  Southwest           0
4   33      Brown  Southwest           0
5   35      Brown  Northeast           0
6   25      Black  Southwest           0
7   52      Brown  Southeast           0

In [107]:
da5_right

Age Hair Color U.S Region  Validation
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Northeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [108]:
pd.merge(da5_left, da5_right, on='U.S Region',how='inner')
pd.merge(da5_left, da5_right, on='U.S Region',how='left')
pd.merge(da5_left, da5_right, on='U.S Region',how='right')

Age_x Hair Color_x U.S Region  Validation_x  Age_y Hair Color_y  \
0      25        Black  Southwest             1     21        Blond   
1      35        Blond  Southwest             0     21        Blond   
2      33        Brown  Southwest             0     21        Blond   
3      25        Black  Southwest             0     21        Blond   
4      45          Red  Northeast             1     24        Blond   
5      35        Brown  Northeast             0     24        Blond   
6      25        Black  Southwest             1     48        Black   
7      35        Blond  Southwest             0     48        Black   
8      33        Brown  Southwest             0     48        Black   
9      25        Black  Southwest             0     48        Black   
10     25        Black  Southwest             1     22        Black   
11     35        Blond  Southwest             0     22        Black   
12     33        Brown  Southwest             0     22        Black   
13     25        Black  Southwest             0     22        Black   
14     45          Red  Northeast             1     27        Brown   
15     35        Brown  Northeast             0     27        Brown   
16     52        Brown  Southeast             0     28        Black   
17     45          Red  Northeast             1     21        Blond   
18     35        Brown  Northeast             0     21        Blond   
19     30        Black  Northwest             1     51        Black   
20     52        Brown  Southeast             0     23        Brown   

    Validation_y  
0              1  
1              1  
2              1  
3              1  
4              0  
5              0  
6              1  
7              1  
8              1  
9              1  
10             0  
11             0  
12             0  
13             0  
14             0  
15             0  
16             1  
17             1  
18             1  
19             0  
20             1

# 15.	Split the below table and perform concat row wise and column wise

In [109]:
pd.concat([da5_left,da5_right] , axis=0)

Age Hair Color U.S Region  Validation
0    25      Black  Southwest           1
1    30      Black  Northwest           1
2    45        Red  Northeast           1
3    35      Blond  Southwest           0
4    33      Brown  Southwest           0
5    35      Brown  Northeast           0
6    25      Black  Southwest           0
7    52      Brown  Southeast           0
8    21      Blond  Southwest           1
9    24      Blond  Northeast           0
10   48      Black  Southwest           1
11   22      Black  Southwest           0
12   27      Brown  Northeast           0
13   28      Black  Southeast           1
14   21      Blond  Northeast           1
15   51      Black  Northwest           0
16   23      Brown  Southeast           1

In [110]:
pd.concat([da5_left,da5_right] , axis=1)

Age Hair Color U.S Region  Validation   Age Hair Color U.S Region  \
0   25.0      Black  Southwest         1.0   NaN        NaN        NaN   
1   30.0      Black  Northwest         1.0   NaN        NaN        NaN   
2   45.0        Red  Northeast         1.0   NaN        NaN        NaN   
3   35.0      Blond  Southwest         0.0   NaN        NaN        NaN   
4   33.0      Brown  Southwest         0.0   NaN        NaN        NaN   
5   35.0      Brown  Northeast         0.0   NaN        NaN        NaN   
6   25.0      Black  Southwest         0.0   NaN        NaN        NaN   
7   52.0      Brown  Southeast         0.0   NaN        NaN        NaN   
8    NaN        NaN        NaN         NaN  21.0      Blond  Southwest   
9    NaN        NaN        NaN         NaN  24.0      Blond  Northeast   
10   NaN        NaN        NaN         NaN  48.0      Black  Southwest   
11   NaN        NaN        NaN         NaN  22.0      Black  Southwest   
12   NaN        NaN        NaN         NaN  27.0      Brown  Northeast   
13   NaN        NaN        NaN         NaN  28.0      Black  Southeast   
14   NaN        NaN        NaN         NaN  21.0      Blond  Northeast   
15   NaN        NaN        NaN         NaN  51.0      Black  Northwest   
16   NaN        NaN        NaN         NaN  23.0      Brown  Southeast   

    Validation  
0          NaN  
1          NaN  
2          NaN  
3          NaN  
4          NaN  
5          NaN  
6          NaN  
7          NaN  
8          1.0  
9          0.0  
10         1.0  
11         0.0  
12         0.0  
13         1.0  
14         1.0  
15         0.0  
16         1.0